# mvn clean install
# docker build . -t email-java
# docker-compose up
# docker-compose down

version: '3.9'

services:
  email-java:
    container_name: email-java
    image: email-java:latest
    ports:
      - "8080:8080"
    networks:
      - chaincue-net
    volumes:
      - ./application.properties:/backend-config/application.properties

networks:
  chaincue-net:
    name: chaincue-net
    driver: bridge

