[package]
name = "mail-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["mail"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mail = { path = "mail" }
