# docker build . -t email-rust
# docker compose up
# docker compose down

version: '3.9'

services:
  email-rust:
    container_name: email-rust
    image: email-rust:latest
    ports:
      - "8080:8080"
    networks:
      - chaincue-net
#    volumes:
#      - ./env:/env

networks:
  chaincue-net:
    name: chaincue-net
    driver: bridge

